apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "couchdb_deployment_name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ template "couchdb_deployment_name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  template:
    metadata:
      labels:
        name: {{ template "couchdb_deployment_name" . }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ template "couchdb_deployment_name" . }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" | quote }}
        image: {{ .Values.image | default "tomxing/openwhisk_couchdb" | quote }}
        command: ["/init.sh"]
        ports:
        - name: couchdb
          containerPort: {{ template "couchdb_port" .}}
        env:
        - name: "DB_HOST"
          value: "127.0.0.1"
        - name: "DB_PREFIX"
          value: {{ .Values.dbPrefix | default "test_" | quote }}
        - name: "DB_USERNAME"
          value: {{ .Values.global.couchdbUserName | default "whisk_admin" | quote }}
        - name: "DB_PASSWORD"
          value: {{ .Values.global.couchdbPassword | default "some_passw0rd" | quote }}
        - name: "DB_PORT"
          value: {{ include "couchdb_port" . | quote }}
